services:
  backend:
    build: .
    container_name: meetup-backend
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: postgres:16-alpine3.20
    container_name: meetup-database
    restart: always
    volumes:
      - ~/containers/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=meetupdb
      - POSTGRES_USER=meetup
    ports:
      - 5432:5432