on:
  push:
    branches:
      - 'develop'
      - 'develop/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Action Checkout
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: python -m pip install --upgrade pip
        run: pip install poetry
        run: poetry lock
        run: poetry install

      - name: Execute tests with pytest
        run: poetry run task test

      - name: Execute docker build
        run: task build