name: Development CI
on:
  push:
    branches:
      - 'develop'
      - 'develop/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'
          cache: 'poetry'
      - name: Install Poetry
        run: pip install poetry
      - name: Install Dependencies
        run: poetry lock; poetry install
      - name: Execute tests with pytest
        run: poetry run task test
