name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: pipx install poetry

      - run: poetry install

      - run: supabase start

      - run: poetry run alembic update head

      - run: poetry run task test

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - run: supabase db push --linked -p $SUPABASE_DB_PASSWORD
